### ISSUE TITLE
[Design] 검색 컴포넌트에 필요한 atomic 컴포넌트 디자인

### ISSUE THREAD

**Issue by yh-project** [kimdw524/coucoupang#4]
## 📔 Description

검색 컴포넌트 디자인 과정에서 필요한 atomic 컴포넌트 디자인

## 🐈 Todo

- [ ] 상품 검색을 위한 input 박스
- [ ] 검색 카테고리 선택을 위한 버튼(선택된 결과, 선택 리스트 각각)
- [ ] 검색 안내를 위한 placeholder
- [ ] 검색 수행을 위한 버튼

**Comment by yh-project** [comment]
input 박스의 경우 @kimdw524 의 TextField atomic component 수정 후 작업 예정
